/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BillingRouteImport } from './routes/billing'
import { Route as BlitzIndexRouteImport } from './routes/blitz.index'
import { Route as BlitzSettingsRouteImport } from './routes/blitz.settings'
import { Route as StudioIndexRouteImport } from './routes/studio.index'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BillingRoute = BillingRouteImport.update({
  id: '/billing',
  path: '/billing',
  getParentRoute: () => rootRouteImport,
} as any)
const BlitzIndexRoute = BlitzIndexRouteImport.update({
  id: '/blitz/',
  path: '/blitz/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlitzSettingsRoute = BlitzSettingsRouteImport.update({
  id: '/blitz/settings',
  path: '/blitz/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const StudioIndexRoute = StudioIndexRouteImport.update({
  id: '/studio/',
  path: '/studio/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/billing': typeof BillingRoute
  '/blitz/settings': typeof BlitzSettingsRoute
  '/blitz/': typeof BlitzIndexRoute
  '/studio/': typeof StudioIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/billing': typeof BillingRoute
  '/blitz/settings': typeof BlitzSettingsRoute
  '/blitz': typeof BlitzIndexRoute
  '/studio': typeof StudioIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/billing': typeof BillingRoute
  '/blitz/settings': typeof BlitzSettingsRoute
  '/blitz/': typeof BlitzIndexRoute
  '/studio/': typeof StudioIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/billing' | '/blitz/settings' | '/blitz/' | '/studio/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/billing' | '/blitz/settings' | '/blitz' | '/studio'
  id: '__root__' | '/' | '/billing' | '/blitz/settings' | '/blitz/' | '/studio/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BillingRoute: typeof BillingRoute
  BlitzSettingsRoute: typeof BlitzSettingsRoute
  BlitzIndexRoute: typeof BlitzIndexRoute
  StudioIndexRoute: typeof StudioIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/billing': {
      id: '/billing'
      path: '/billing'
      fullPath: '/billing'
      preLoaderRoute: typeof BillingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blitz/': {
      id: '/blitz/'
      path: '/blitz'
      fullPath: '/blitz/'
      preLoaderRoute: typeof BlitzIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blitz/settings': {
      id: '/blitz/settings'
      path: '/blitz/settings'
      fullPath: '/blitz/settings'
      preLoaderRoute: typeof BlitzSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/studio/': {
      id: '/studio/'
      path: '/studio'
      fullPath: '/studio/'
      preLoaderRoute: typeof StudioIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BillingRoute: BillingRoute,
  BlitzSettingsRoute: BlitzSettingsRoute,
  BlitzIndexRoute: BlitzIndexRoute,
  StudioIndexRoute: StudioIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
